/** Edge/SQL publication bounds. Keep the identically named SQL constants in sync. */
export const BENEFIT_PUBLICATION_LIMITS = Object.freeze({
  MAX_DECISIONS: 64,
  MAX_CANONICAL_ARRAY_ITEMS: 64,
  MAX_CANONICAL_STRING_CHARS: 500,
  MAX_CONDITION_BYTES: 32768,
  MAX_BENEFIT_BYTES: 65536,
  MAX_ENVELOPE_BYTES: 131072,
  MAX_REVIEW_BYTES: 262144,
  MAX_SOURCE_EVIDENCE_ITEMS: 32,
  MAX_SOURCE_EVIDENCE_BYTES: 32768,
  MAX_CANONICAL_DEPTH: 8,
  MAX_CANONICAL_KEYS: 256,
  MAX_STAGED_PROPOSALS: 64,
});

/** Presentation-only work bounds; overflow returns an explicit invalid marker. */
export const BENEFIT_ADMIN_PRESENTATION_LIMITS = Object.freeze({
  MAX_ADMIN_DTO_BYTES: 131072,
  MAX_ADMIN_ARRAY_ITEMS: 128,
  MAX_ADMIN_OBJECT_KEYS: 128,
  MAX_ADMIN_DEPTH: 10,
  MAX_ADMIN_STRING_CHARS: 8000,
  MAX_ADMIN_KEY_CHARS: 500,
  MAX_ADMIN_WORK_ITEMS: 2048,
});
