import 'package:cardcompass/shared/models/transaction.dart';
import 'package:cardcompass/shared/models/credit_card.dart';
import 'package:cardcompass/shared/models/benefit.dart';
import 'package:cardcompass/shared/models/benefit_tracking.dart';
import 'package:cardcompass/core/repositories/supabase_benefit_tracking_repository.dart';
import 'package:cardcompass/core/repositories/supabase_notification_repository.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Provider for benefit tracking service
final benefitTrackingServiceProvider = Provider<BenefitTrackingService>((ref) {
  return BenefitTrackingService(ref);
});

/// Service for automatically tracking benefit usage from transactions
class BenefitTrackingService {
  late final SupabaseBenefitTrackingRepository _trackingRepository;
  late final SupabaseNotificationRepository _notificationRepository;

  BenefitTrackingService(Ref ref) {
    _trackingRepository = SupabaseBenefitTrackingRepository();
    _notificationRepository = SupabaseNotificationRepository();
  }

  /// Process a transaction and record any applicable benefits
  Future<List<BenefitUsageRecord>> processTransactionBenefits({
    required Transaction transaction,
    required CreditCard card,
    required String userId,
  }) async {
    final records = <BenefitUsageRecord>[];

    try {
      // Process each benefit on the card
      for (final benefit in card.benefits) {
        if (!benefit.isActive) continue;

        final benefitUsage = await _calculateBenefitUsage(
          transaction: transaction,
          card: card,
          benefit: benefit,
          userId: userId,
        );

        if (benefitUsage != null) {
          // Record the benefit usage
          final record = await _trackingRepository.recordBenefitUsage(benefitUsage);
          records.add(record);

          // Create notification for significant benefits
          if (benefitUsage.benefitValue >= 50) {
            await _createBenefitNotification(
              userId: userId,
              record: record,
              card: card,
            );
          }
        }
      }

      // Check for milestone achievements
      await _checkMilestones(userId, transaction, card);

    } catch (e) {
      // Log error but don't fail the transaction processing
      print('Error processing transaction benefits: $e');
    }

    return records;
  }

  /// Calculate benefit usage for a specific benefit
  Future<BenefitUsageRecord?> _calculateBenefitUsage({
    required Transaction transaction,
    required CreditCard card,
    required Benefit benefit,
    required String userId,
  }) async {
    double benefitValue = 0;
    String benefitType = '';    // Check if transaction category matches benefit
    if (!_categoryMatches(transaction.category.toString(), benefit.categoryCode)) {
      return null;
    }

    // Calculate benefit based on type
    switch (benefit.calculationMethod) {
      case 'percentage':
        benefitValue = transaction.amount * ((benefit.defaultValue ?? 0) / 100);
        benefitType = 'cashback';
        break;
      case 'fixed':
        benefitValue = benefit.defaultValue ?? 0;
        benefitType = 'fixed_reward';
        break;
      case 'points':
        benefitValue = transaction.amount * (benefit.defaultValue ?? 0); // Points earned
        benefitType = 'points';
        break;
      case 'miles':
        benefitValue = transaction.amount * (benefit.defaultValue ?? 0); // Miles earned
        benefitType = 'miles';
        break;
      case 'boolean':
        // Benefits like lounge access, insurance - no monetary value
        if ((benefit.defaultValue ?? 0) > 0) {
          benefitValue = 0; // No direct monetary benefit
          benefitType = 'access';
        }
        break;
      default:
        return null;
    }

    if (benefitValue <= 0 && benefitType != 'access') {
      return null;
    }

    return BenefitUsageRecord(
      id: '', // Will be generated by database
      userId: userId,
      userCardId: card.id,
      benefitId: benefit.id,
      transactionId: transaction.id,
      transactionAmount: transaction.amount,
      benefitValue: benefitValue,
      benefitType: benefitType,
      usageDate: transaction.transactionDate,
      category: transaction.category.toString(),
      merchantName: transaction.description,
      metadata: {
        'benefit_name': benefit.name,
        'calculation_method': benefit.calculationMethod,
        'original_value': benefit.defaultValue,
        'card_name': card.cardName,
      },
      createdAt: DateTime.now(),
    );
  }

  /// Check if transaction category matches benefit category
  bool _categoryMatches(String transactionCategory, String benefitCategory) {
    // Normalize categories
    final txCategory = transactionCategory.toLowerCase();
    final benefitCat = benefitCategory.toLowerCase();

    // Direct match
    if (txCategory == benefitCat) return true;

    // Category mappings
    final categoryMappings = {
      'dining': ['restaurant', 'food', 'zomato', 'swiggy', 'uber_eats'],
      'fuel': ['petrol', 'diesel', 'gas_station', 'fuel_station'],
      'grocery': ['supermarket', 'grocery_store', 'walmart', 'target'],
      'online': ['ecommerce', 'amazon', 'flipkart', 'online_shopping'],
      'travel': ['airline', 'hotel', 'booking', 'makemytrip'],
      'entertainment': ['movie', 'cinema', 'netflix', 'spotify'],
      'utility': ['electricity', 'water', 'gas_bill', 'phone_bill'],
    };

    // Check if transaction category matches any mapped values
    for (final entry in categoryMappings.entries) {
      if (entry.key == benefitCat && entry.value.contains(txCategory)) {
        return true;
      }
    }

    return false;
  }

  /// Create notification for benefit usage
  Future<void> _createBenefitNotification({
    required String userId,
    required BenefitUsageRecord record,
    required CreditCard card,
  }) async {
    try {
      String title;
      String message;

      switch (record.benefitType) {
        case 'cashback':
          title = 'Cashback Earned!';
          message = 'You earned ₹${record.benefitValue.toStringAsFixed(0)} cashback on your ${card.cardName} for ${record.merchantName}';
          break;
        case 'points':
          title = 'Points Earned!';
          message = 'You earned ${record.benefitValue.toStringAsFixed(0)} points on your ${card.cardName} for ${record.merchantName}';
          break;
        case 'miles':
          title = 'Miles Earned!';
          message = 'You earned ${record.benefitValue.toStringAsFixed(0)} miles on your ${card.cardName} for ${record.merchantName}';
          break;
        default:
          title = 'Benefit Used!';
          message = 'You used a benefit on your ${card.cardName} for ${record.merchantName}';
      }

      await _notificationRepository.createBenefitAlert(
        userId: userId,
        title: title,
        message: message,
        benefitId: record.benefitId,
        cardId: record.userCardId,
        savingsAmount: record.benefitValue,
      );
    } catch (e) {
      print('Error creating benefit notification: $e');
    }
  }

  /// Check for spending milestones and achievements
  Future<void> _checkMilestones(String userId, Transaction transaction, CreditCard card) async {
    try {
      final now = DateTime.now();
      final monthStart = DateTime(now.year, now.month, 1);
      
      // Get monthly spending summary
      final summary = await _trackingRepository.getBenefitUsageSummary(
        userId,
        startDate: monthStart,
        endDate: now,
      );

      final monthlySpending = summary['total_spending'] as double? ?? 0;
      final monthlySavings = summary['total_savings'] as double? ?? 0;

      // Check spending milestones
      final milestones = [1000, 5000, 10000, 25000, 50000];
      for (final milestone in milestones) {
        if (monthlySpending >= milestone && monthlySpending - transaction.amount < milestone) {        await _createMilestoneNotification(
          userId: userId,
          milestone: milestone.toDouble(),
          totalSavings: monthlySavings,
        );
          break;
        }
      }

      // Check savings milestones
      final savingsMilestones = [100, 500, 1000, 2500, 5000];
      for (final milestone in savingsMilestones) {
        if (monthlySavings >= milestone) {
          // Check if this is a new milestone
          final lastMonthSummary = await _trackingRepository.getBenefitUsageSummary(
            userId,
            startDate: DateTime(now.year, now.month - 1, 1),
            endDate: DateTime(now.year, now.month, 1).subtract(const Duration(days: 1)),
          );
          
          final lastMonthSavings = lastMonthSummary['total_savings'] as double? ?? 0;
          
          if (lastMonthSavings < milestone) {          await _createSavingsMilestoneNotification(
            userId: userId,
            milestone: milestone.toDouble(),
            monthlySpending: monthlySpending,
          );
          }
          break;
        }
      }
    } catch (e) {
      print('Error checking milestones: $e');
    }
  }

  /// Create milestone notification
  Future<void> _createMilestoneNotification({
    required String userId,
    required double milestone,
    required double totalSavings,
  }) async {
    try {
      await _notificationRepository.createSpendingInsight(
        userId: userId,
        title: 'Spending Milestone Reached!',
        message: 'You\'ve spent ₹${milestone.toStringAsFixed(0)} this month and saved ₹${totalSavings.toStringAsFixed(0)} through your credit cards!',
        amount: milestone,
      );
    } catch (e) {
      print('Error creating milestone notification: $e');
    }
  }

  /// Create savings milestone notification
  Future<void> _createSavingsMilestoneNotification({
    required String userId,
    required double milestone,
    required double monthlySpending,
  }) async {
    try {
      final savingsRate = (milestone / monthlySpending) * 100;
      
      await _notificationRepository.createSpendingInsight(
        userId: userId,
        title: 'Savings Milestone Achieved!',
        message: 'Congratulations! You\'ve saved ₹${milestone.toStringAsFixed(0)} this month (${savingsRate.toStringAsFixed(1)}% savings rate)!',
        amount: milestone,
      );
    } catch (e) {
      print('Error creating savings milestone notification: $e');
    }
  }

  /// Generate benefit recommendations based on usage patterns
  Future<void> generateBenefitRecommendations(String userId) async {
    try {
      final analytics = await _trackingRepository.getBenefitAnalytics(
        userId,
        period: 'month',
      );

      // Analyze top spending categories
      final topCategories = analytics.categoryWiseSavings.entries
          .toList()
          ..sort((a, b) => b.value.compareTo(a.value));

      for (final entry in topCategories.take(3)) {
        final category = entry.key;
        final savings = entry.value;
        
        // Check if user can get better benefits in this category
        await _checkBetterBenefitOptions(userId, category, savings);
      }
    } catch (e) {
      print('Error generating benefit recommendations: $e');
    }
  }

  /// Check for better benefit options in a category
  Future<void> _checkBetterBenefitOptions(String userId, String category, double currentSavings) async {
    // This would typically query a database of available cards/benefits
    // For now, create a simple recommendation
    
    final potentialSavings = currentSavings * 1.5; // 50% improvement potential
    
    if (potentialSavings - currentSavings >= 100) { // Only recommend if savings > ₹100
      await _notificationRepository.createCardRecommendation(
        userId: userId,
        title: 'Better ${category.toUpperCase()} Benefits Available',
        message: 'You could save an additional ₹${(potentialSavings - currentSavings).toStringAsFixed(0)} annually with a card that offers better $category benefits.',
        cardId: 'recommended_card', // Would be actual card ID
        potentialSavings: potentialSavings - currentSavings,
      );
    }
  }
}
