-- supabase/migrations/20260817010000_hsbc_travelone_movie_benefit.sql
--
-- HSBC TravelOne was missing from card_catalog entirely — not present in
-- 20260711043900_restore_reference_data.sql's bulk seed, and not covered by
-- 20260802100000_curated_movie_benefit_mappings.sql's curated set (which
-- only mapped 6 pre-existing IDFC FIRST/Axis/HDFC cards). This account owns
-- the card but the card itself, its movie benefit, and the ownership link
-- all needed adding.
--
-- Movie benefit terms verified against two first-party sources (not an
-- aggregator paraphrase):
--   - https://www.hsbc.co.in/credit-cards/products/travelone/ — states the
--     District by Zomato BOGO offer redeems "twice a month" (promo code
--     HSBCTOMOV mentioned on-page, not stored here since it's a redemption
--     mechanic on District's own app, not a card_benefit_mapping concern).
--   - https://www.district.in/hsbc-campaign — District's own dedicated HSBC
--     campaign page states the free ticket is capped "up to ₹250".
-- A third-party aggregator's "₹200 cap, once a month" figure was checked
-- and rejected as less authoritative than the above two first-party pages.
--
-- Follows the same conventions as 20260802100000_curated_movie_benefit_mappings.sql:
-- ILIKE with no wildcards to avoid ambiguous substring matches, ON CONFLICT
-- DO NOTHING throughout, and no hardcoded UUIDs — every row is located by a
-- stable natural key (card_name, benefit title, or auth.users.email) so this
-- migration is safe to re-run and does not depend on any ID generated by a
-- previous, non-reproducible run.
BEGIN;

-- card_catalog: HSBC TravelOne does not exist under any name/spelling in the
-- bulk-restored reference data (grepped for "hsbc" and "travelone" across
-- every migration — zero matches before this one).
INSERT INTO card_catalog (bank, card_name, network, card_type, card_url)
SELECT 'HSBC', 'TravelOne', 'Visa', 'Credit', 'https://www.hsbc.co.in/credit-cards/products/travelone/'
WHERE NOT EXISTS (
  SELECT 1 FROM card_catalog WHERE card_name ILIKE 'TravelOne' AND bank ILIKE 'HSBC'
);

-- benefits: "Buy 1 Get 1 on Movies" (bogo, District by Zomato). value_config
-- keys match movie_deal_rule_normalizer.dart's _normalizeBogo exactly:
-- max_discount_per_transaction (caps the free ticket, NOT a cycle total —
-- perTransactionCap in the normalizer) and max_usage_per_month (redemption
-- COUNT, never a ticket count — cycleRedemptionLimit in the normalizer).
--
-- partners is JSONB here, not TEXT[] — 20260711043700_fix_benefit_column_types.sql
-- converted it shortly after the initial schema (the stale TEXT[] in
-- 20260711043541_initial_schema.sql's CREATE TABLE was never updated to
-- match). Every real row in 20260711043900_restore_reference_data.sql
-- stores it as a JSON array literal (e.g. ["IndiGo"]), confirming this —
-- use jsonb_build_array, not ARRAY[...], to match the actual column type.
--
-- dedupe_key: 20260713180753_normalize_card_benefit_mappings.sql added this
-- column with a NOT NULL constraint + a UNIQUE INDEX, computed as
-- lower(category)|lower(type)|lower(title) (whitespace-normalized). Neither
-- 20260711043541_initial_schema.sql nor the type-fix migration mentions it —
-- it was added later and this repo's tracked history doesn't surface it
-- until you actually try to INSERT, the same way partners' JSONB type
-- didn't surface until the previous run of this same migration errored.
-- Computed inline via the identical expression the original migration used
-- (never hand-computed and hardcoded as a literal) so it cannot silently
-- drift from the title/category actually being inserted on this same row.
INSERT INTO benefits (title, description, benefit_category, value_config, partners, source_url, dedupe_key)
SELECT
  'HSBC TravelOne Movie BOGO',
  'Buy 1 movie ticket, get 1 free on District by Zomato. Free ticket capped at ₹250, redeemable twice a month.',
  'entertainment',
  jsonb_build_object(
    'category', 'movie',
    'discount_type', 'bogo',
    'max_discount_per_transaction', 250,
    'max_usage_per_month', 2
  ),
  jsonb_build_array('District'),
  'https://www.district.in/hsbc-campaign',
  -- benefit_type is not set on this row (left NULL, same as most real
  -- movie-benefit rows in restore_reference_data.sql) — the middle segment
  -- coalesces to '', exactly like the original migration's own formula.
  lower(regexp_replace(trim('entertainment'), '\s+', ' ', 'g'))
    || '|' || ''
    || '|' || lower(regexp_replace(trim('HSBC TravelOne Movie BOGO'), '\s+', ' ', 'g'))
WHERE NOT EXISTS (
  SELECT 1 FROM benefits WHERE title = 'HSBC TravelOne Movie BOGO'
);

-- card_benefit_mapping: link the new benefit to the new card. Exact,
-- unambiguous match — HSBC has only one card_catalog row named "TravelOne",
-- unlike the Millennia/Wealth/Diners Club Black cases the earlier curated
-- migration had to disambiguate against.
INSERT INTO card_benefit_mapping (card_id, benefit_id, display_priority)
SELECT c.id, b.benefit_id, 1
FROM card_catalog c, benefits b
WHERE c.card_name ILIKE 'TravelOne'
  AND c.bank ILIKE 'HSBC'
  AND b.title = 'HSBC TravelOne Movie BOGO'
ON CONFLICT DO NOTHING;

-- user_cards: link this account's ownership. Located by auth.users.email —
-- never a hardcoded UUID — so this migration carries no dependency on a
-- prior non-reproducible run and is safe to read by anyone auditing this
-- file without exposing or guessing at an internal user id.
INSERT INTO user_cards (user_id, catalog_card_id, is_active)
SELECT u.id, c.id, true
FROM auth.users u, card_catalog c
WHERE u.email = 'shantanu.msp@gmail.com'
  AND c.card_name ILIKE 'TravelOne'
  AND c.bank ILIKE 'HSBC'
ON CONFLICT (user_id, catalog_card_id) DO NOTHING;

COMMIT;
