-- Harden functions and tables created during backend recovery.

-- User-scoped RPCs execute as the caller so existing RLS policies enforce
-- auth.uid() = user_id.
ALTER FUNCTION public.add_transaction(uuid, uuid, numeric, text, timestamptz, text, text, text, text, text) SECURITY INVOKER SET search_path = public;
ALTER FUNCTION public.associate_user_with_card(uuid, uuid, text, text, text, text, numeric, integer, integer) SECURITY INVOKER SET search_path = public;
ALTER FUNCTION public.get_user_cards(uuid) SECURITY INVOKER SET search_path = public;
ALTER FUNCTION public.get_user_transactions(uuid, integer) SECURITY INVOKER SET search_path = public;
ALTER FUNCTION public.remove_user_card(uuid, uuid) SECURITY INVOKER SET search_path = public;
ALTER FUNCTION public.update_user_card(uuid, uuid, text, numeric, text, text, integer, integer) SECURITY INVOKER SET search_path = public;

REVOKE ALL ON FUNCTION public.add_transaction(uuid, uuid, numeric, text, timestamptz, text, text, text, text, text) FROM anon;
REVOKE ALL ON FUNCTION public.associate_user_with_card(uuid, uuid, text, text, text, text, numeric, integer, integer) FROM anon;
REVOKE ALL ON FUNCTION public.get_user_cards(uuid) FROM anon;
REVOKE ALL ON FUNCTION public.get_user_transactions(uuid, integer) FROM anon;
REVOKE ALL ON FUNCTION public.remove_user_card(uuid, uuid) FROM anon;
REVOKE ALL ON FUNCTION public.update_user_card(uuid, uuid, text, numeric, text, text, integer, integer) FROM anon;

-- Catalog writes are administrative. Client applications may read the catalog
-- but cannot create or mutate global reference data.
-- Remove legacy RPCs that target columns/tables absent from the recovered
-- schema. They are unused by the app and fail database linting.
DROP FUNCTION IF EXISTS public.associate_card_with_user(uuid, uuid, text);
DROP FUNCTION IF EXISTS public.create_credit_card(uuid, text, text, text, text, numeric, boolean);
DROP FUNCTION IF EXISTS public.insert_transaction_with_card_id(uuid, uuid, uuid, numeric, text, timestamptz, text, text, text);

REVOKE ALL ON FUNCTION public.create_or_get_card_catalog(text, text, text, text, numeric, numeric, numeric) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_or_get_card_catalog(text, text, text, text, numeric, numeric, numeric) TO service_role;
ALTER FUNCTION public.create_or_get_card_catalog(text, text, text, text, numeric, numeric, numeric) SET search_path = public;

ALTER FUNCTION public.get_card_catalog() SECURITY INVOKER SET search_path = public;
REVOKE ALL ON FUNCTION public.get_card_catalog() FROM anon;

-- Approval data is service-role only.
ALTER TABLE public.card_benefits_staging ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.card_benefits_staging FROM anon, authenticated;
GRANT ALL ON TABLE public.card_benefits_staging TO service_role;

-- Gmail message IDs are scoped to a mailbox, not globally unique.
ALTER TABLE public.emails DROP CONSTRAINT IF EXISTS emails_email_id_key;
DROP INDEX IF EXISTS public.idx_emails_email_id;
CREATE UNIQUE INDEX IF NOT EXISTS idx_emails_user_email_id
  ON public.emails(user_id, email_id);

-- Durable per-user rate-limit ledger for the authenticated Gemini proxy.
CREATE TABLE IF NOT EXISTS public.gemini_proxy_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gemini_proxy_usage_user_created
  ON public.gemini_proxy_usage(user_id, created_at DESC);
ALTER TABLE public.gemini_proxy_usage ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.gemini_proxy_usage FROM anon, authenticated;
GRANT ALL ON TABLE public.gemini_proxy_usage TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.gemini_proxy_usage_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.consume_gemini_proxy_quota(
  _user_id uuid,
  _limit integer DEFAULT 10
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  recent_count integer;
BEGIN
  IF _user_id IS NULL OR _limit < 1 OR _limit > 60 THEN
    RETURN false;
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext(_user_id::text));
  DELETE FROM public.gemini_proxy_usage
    WHERE created_at < now() - interval '1 hour';
  SELECT count(*) INTO recent_count
    FROM public.gemini_proxy_usage
    WHERE user_id = _user_id
      AND created_at >= now() - interval '1 minute';
  IF recent_count >= _limit THEN
    RETURN false;
  END IF;
  INSERT INTO public.gemini_proxy_usage(user_id) VALUES (_user_id);
  RETURN true;
END;
$$;
REVOKE ALL ON FUNCTION public.consume_gemini_proxy_quota(uuid, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_gemini_proxy_quota(uuid, integer)
  TO service_role;

-- Catalog requests are deduplicated and capped atomically per user.
ALTER TABLE public.card_benefits_staging
  ADD COLUMN IF NOT EXISTS requested_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_card_staging_requester_url
  ON public.card_benefits_staging(requested_by, source_url)
  WHERE requested_by IS NOT NULL;

CREATE OR REPLACE FUNCTION public.submit_card_catalog_request(
  _user_id uuid,
  _bank_name text,
  _card_name text,
  _card_url text
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  pending_count integer;
BEGIN
  IF _user_id IS NULL OR length(_bank_name) NOT BETWEEN 2 AND 100
     OR length(_card_name) NOT BETWEEN 2 AND 150
     OR length(_card_url) > 2048 THEN
    RETURN false;
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('catalog:' || _user_id::text));
  IF EXISTS (
    SELECT 1 FROM public.card_benefits_staging
    WHERE requested_by = _user_id AND source_url = _card_url
  ) THEN
    RETURN true;
  END IF;
  SELECT count(*) INTO pending_count
    FROM public.card_benefits_staging
    WHERE requested_by = _user_id AND status = 'pending';
  IF pending_count >= 10 THEN
    RETURN false;
  END IF;
  INSERT INTO public.card_benefits_staging(
    source_url, extracted_data, status, requested_by
  ) VALUES (
    _card_url,
    jsonb_build_object(
      'request_type', 'catalog_entry',
      'bank_name', _bank_name,
      'card_name', _card_name
    ),
    'pending',
    _user_id
  );
  RETURN true;
END;
$$;
REVOKE ALL ON FUNCTION public.submit_card_catalog_request(uuid, text, text, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_card_catalog_request(uuid, text, text, text)
  TO service_role;
